name: ocr
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.7+13

environment:
  sdk: ">=2.7.0 <3.0.0"
 
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_easyloading: ^3.0.0
  flutter_typeahead: ^4.1.1
  http: ^0.13.4 
  intl: ^0.18.0 
  multi_select_flutter: ^4.0.0
  permission_handler: ^10.2.0
  shared_preferences: ^2.0.17
  image_picker: ^0.8.3+3
  image_cropper: ^3.0.1
  crop: ^0.5.1+1
  simple_corner_detection:
    path: /Users/codesncoffee/Desktop/simple_corner_detection  
  path_provider: ^2.0.2
  provider: ^6.0.5
  pdf: ^3.7.4
  pull_to_refresh: ^2.0.0
  flutter_pdfview: ^1.2.1
  auto_size_text: ^3.0.0
  native_pdf_renderer: ^5.0.0+1
  camera: ^0.10.2+1
  thumbnailer: ^2.0.1
  device_information: ^0.0.4
  
dependency_overrides:
  camera_android:
    git:
      url: https://github.com/elmar001/plugins.git
      path: packages/camera/camera_android
      ref: 5172b44088a4082ff0899594614c5380457d341b
      
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/